In [1]:
import sys
import importlib
import numpy as np
import pandas as pd
import uproot
import matplotlib.pyplot as plt
import sys
import awkward as ak
import scipy
import ROOT
sys.path.insert(0,"../")

Welcome to JupyROOT 6.30/07

In [2]:
sys.path.insert(0,"../../python/HNL_Plotting_HelperFunctions")
import MuonSystemReader
import Produce_Cutflow_v2
import analysis_helpers
import Processing_Helpers

/cvmfs/cms.cern.ch/el9_amd64_gcc12/lcg/root/6.30.07-024df6516c17fd2edef848a927a788f1/lib/ROOT/_facade.py:154: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  return _orig_ihook(name, *args, **kwds)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)

In [3]:
importlib.reload(Produce_Cutflow_v2)
#importlib.reload(Processing_Helpers)

<module 'Produce_Cutflow_v2' from '/uscms_data/d3/amalbert/el9_work/CMSSW_14_1_0_pre4/src/run3_llp_analyzer/HNL_Plotting_Scripts/ABCD_Closure_Studies/../../python/HNL_Plotting_HelperFunctions/Produce_Cutflow_v2.py'>

In [4]:
data_path_base = "root://cmseos.fnal.gov//store/group/lpclonglived/amalbert/HNL_Tau_Search/2024_Data_e_analyzer_update_012026/"
data_events_list = Processing_Helpers.make_data_list(data_path_base, 'e')
data_events_e  = MuonSystemReader.loadTree_nanoFactory(data_events_list)

data_path_base = "root://cmseos.fnal.gov//store/group/lpclonglived/amalbert/HNL_Tau_Search/2024_Data_mu/"
data_events_list = Processing_Helpers.make_data_list(data_path_base, 'mu')
data_events_mu  = MuonSystemReader.loadTree_nanoFactory(data_events_list)

data_path_base = "root://cmseos.fnal.gov//store/group/lpclonglived/amalbert/HNL_Tau_Search/2024_Data_tauh_analyzer_update_012026/"
data_events_list = Processing_Helpers.make_data_list(data_path_base, 'tau')
data_events_tau  = MuonSystemReader.loadTree_nanoFactory(data_events_list)

/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/factory.py:317: RuntimeWarning: You have set steps_per_file to 4, this should only be used for a
                small number of inputs (e.g. for early-stage/exploratory analysis) since it does not
                inform dask of each chunk lengths at creation time, which can cause unexpected
                slowdowns at scale. If you would like to process larger datasets please specify steps
                using the appropriate uproot "files" specification:
                    https://github.com/scikit-hep/uproot5/blob/v5.1.2/src/uproot/_dask.py#L109-L132.

  warnings.warn(
/uscms/home/amalbert/.local/lib/python3.9/site-packages/dask_awkward/lib/structure.py:911: UserWarning: Please ensure that dask.awkward<nCscRechitClusters, npartitions=80>
        is partitionwise-compatible with dask.awkward<getitem, npartitions=80>
        (e.g. counts comes from a dak.num(array, axis=1)),
        otherwise this unflatten operation will fail when computed!
  warnings.warn(

## for e-type data

### MVAIDISO, noHT

In [5]:
cutflow_data, ABCD_data = Produce_Cutflow_v2.makeCutflow(data_events_e, cfg_file='e_VR_DNN/cuts_sensitivity_e_DNN_MVAISO_VR1.yaml', isMC=False, ABCD=True, blind=False, flavor="Ele", return_branches=False)
cutflow_data

about to compute
entering ABCD code

,Cut Name,Number of Weighted Events,Number of Unweighted Events,Cut Efficiency,Cumulative Efficiency
0,Pass Trigger,4282995.0,4282995,0.881249,0.881249
1,MET>30 GeV,2050061.0,2050061,0.478651,0.421811
2,nLeptons==1,1867581.0,1867581,0.910988,0.384265
3,Lepton is Electron,1136052.0,1136052,0.608301,0.233749
4,-5ns<clusterTime<12.5ns,914252.0,914252,0.804762,0.188112
5,no hits ME1112,907388.0,907388,0.992492,0.186700
6,MuonVetoPt<30GeV,898728.0,898728,0.990456,0.184918
7,JetVetoPt<10 GeV,797952.0,797952,0.887868,0.164183
8,"|dPhi(cluster, MET)|<1.5",398030.0,398030,0.498814,0.081897
9,elePt>15GeV,18247.0,18247,0.045843,0.003754
10,ele pass MVAISO80,2297.0,2297,0.125884,0.000473
11,"|DeltaEta(cluster,ele)|<2",1392.0,1392,0.606008,0.000286
12,0.96<DNN<0.99,252.0,252,0.181034,0.000052

/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)

In [6]:
ABCD_data

                             Bin                     Counts
0    bin A (low NHits, low dPhi)  82.0 +- 9.055385138137417
1   bin B (low NHits, high dPhi)   73.0 +- 8.54400374531753
2   bin C (high NHits, low dPhi)  63.0 +- 7.937253933193772
3  bin D (high NHits, high dPhi)   66.0 +- 8.12403840463596

In [7]:
arr = analysis_helpers.extract_counts_uncs_from_df(ABCD_data)
D_exp, D_exp_unc = analysis_helpers.compute_expected_signal_bin(*arr)
print(f"{D_exp}+-{D_exp_unc}")

56.08536585365854+-11.46212108400295

### MVAISO, with HT Cut

In [8]:
cutflow_data, ABCD_data = Produce_Cutflow_v2.makeCutflow(data_events_e, cfg_file='e_VR_DNN/cuts_sensitivity_e_DNN_MVAISO_HT_VR1.yaml', isMC=False, ABCD=True, blind=False, flavor="Ele", return_branches=False)
cutflow_data

about to compute
entering ABCD code

,Cut Name,Number of Weighted Events,Number of Unweighted Events,Cut Efficiency,Cumulative Efficiency
0,Pass Trigger,4282995.0,4282995,0.881249,0.881249
1,MET>30 GeV,2050061.0,2050061,0.478651,0.421811
2,nLeptons==1,1867581.0,1867581,0.910988,0.384265
3,Lepton is Electron,1136052.0,1136052,0.608301,0.233749
4,-5ns<clusterTime<12.5ns,914252.0,914252,0.804762,0.188112
5,no hits ME1112,907388.0,907388,0.992492,0.186700
6,MuonVetoPt<30GeV,898728.0,898728,0.990456,0.184918
7,JetVetoPt<10 GeV,797952.0,797952,0.887868,0.164183
8,"|dPhi(cluster, MET)|<1.5",398030.0,398030,0.498814,0.081897
9,elePt>15GeV,18247.0,18247,0.045843,0.003754
10,ele pass MVAISO80,2297.0,2297,0.125884,0.000473
11,"|DeltaEta(cluster,ele)|<2",1392.0,1392,0.606008,0.000286
12,0.96<DNN<0.99,252.0,252,0.181034,0.000052
13,HTSoftJetsEtaLargerThan3.139<20,96.0,96,0.380952,0.000020

/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)

In [9]:
ABCD_data

                             Bin                     Counts
0    bin A (low NHits, low dPhi)  28.0 +- 5.291502622129181
1   bin B (low NHits, high dPhi)                25.0 +- 5.0
2   bin C (high NHits, low dPhi)  24.0 +- 4.898979485566356
3  bin D (high NHits, high dPhi)  27.0 +- 5.196152422706632

In [10]:
arr = analysis_helpers.extract_counts_uncs_from_df(ABCD_data)
D_exp, D_exp_unc = analysis_helpers.compute_expected_signal_bin(*arr)
print(f"{D_exp}+-{D_exp_unc}")

21.42857142857143+-7.341622226022053

### Cut-based ID, no HT

In [11]:
cutflow_data, ABCD_data = Produce_Cutflow_v2.makeCutflow(data_events_e, cfg_file='e_VR_DNN/cuts_sensitivity_e_DNN_CutBased_VR1.yaml', isMC=False, ABCD=True, blind=False, flavor="Ele", return_branches=False)
cutflow_data

about to compute
entering ABCD code

2026-02-10 17:39:28,054 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing

,Cut Name,Number of Weighted Events,Number of Unweighted Events,Cut Efficiency,Cumulative Efficiency
0,Pass Trigger,4282995.0,4282995,0.881249,0.881249
1,MET>30 GeV,2050061.0,2050061,0.478651,0.421811
2,nLeptons==1,1867581.0,1867581,0.910988,0.384265
3,Lepton is Electron,1136052.0,1136052,0.608301,0.233749
4,-5ns<clusterTime<12.5ns,914252.0,914252,0.804762,0.188112
5,no hits ME1112,907388.0,907388,0.992492,0.186700
6,MuonVetoPt<30GeV,898728.0,898728,0.990456,0.184918
7,JetVetoPt<10 GeV,797952.0,797952,0.887868,0.164183
8,"|dPhi(cluster, MET)|<1.5",398030.0,398030,0.498814,0.081897
9,elePt>15GeV,18247.0,18247,0.045843,0.003754
10,ele fail cut-based tightID,7071.0,7071,0.387516,0.001455
11,ele pass looseISO,7068.0,7068,0.999576,0.001454
12,"|DeltaEta(cluster,ele)|<2",4045.0,4045,0.572298,0.000832
13,0.96<DNN<0.99,739.0,739,0.182695,0.000152

/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)

In [12]:
ABCD_data

                             Bin                       Counts
0    bin A (low NHits, low dPhi)  263.0 +- 16.217274740226856
1   bin B (low NHits, high dPhi)  239.0 +- 15.459624833740307
2   bin C (high NHits, low dPhi)   174.0 +- 13.19090595827292
3  bin D (high NHits, high dPhi)   168.0 +- 12.96148139681572

In [13]:
arr = analysis_helpers.extract_counts_uncs_from_df(ABCD_data)
D_exp, D_exp_unc = analysis_helpers.compute_expected_signal_bin(*arr)
print(f"{D_exp}+-{D_exp_unc}")

158.12167300380227+-18.530287038634587

### Cut-based ID, HT

In [14]:
cutflow_data, ABCD_data = Produce_Cutflow_v2.makeCutflow(data_events_e, cfg_file='e_VR_DNN/cuts_sensitivity_e_DNN_CutBased_HT_VR1.yaml', isMC=False, ABCD=True, blind=False, flavor="Ele", return_branches=False)
cutflow_data

/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/python3/3.9.14-c10287ae9cadff55334e60003302c349/lib/python3.9/contextlib.py:126: UserWarning: Creating scratch directories is taking a surprisingly long time. (1.37s) This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)

about to compute
entering ABCD code

,Cut Name,Number of Weighted Events,Number of Unweighted Events,Cut Efficiency,Cumulative Efficiency
0,Pass Trigger,4282995.0,4282995,0.881249,0.881249
1,MET>30 GeV,2050061.0,2050061,0.478651,0.421811
2,nLeptons==1,1867581.0,1867581,0.910988,0.384265
3,Lepton is Electron,1136052.0,1136052,0.608301,0.233749
4,-5ns<clusterTime<12.5ns,914252.0,914252,0.804762,0.188112
5,no hits ME1112,907388.0,907388,0.992492,0.186700
6,MuonVetoPt<30GeV,898728.0,898728,0.990456,0.184918
7,JetVetoPt<10 GeV,797952.0,797952,0.887868,0.164183
8,"|dPhi(cluster, MET)|<1.5",398030.0,398030,0.498814,0.081897
9,elePt>15GeV,18247.0,18247,0.045843,0.003754
10,ele fail cut-based tightID,7071.0,7071,0.387516,0.001455
11,ele pass looseISO,7068.0,7068,0.999576,0.001454
12,"|DeltaEta(cluster,ele)|<2",4045.0,4045,0.572298,0.000832
13,0.96<DNN<0.99,739.0,739,0.182695,0.000152
14,HTSoftJetsEtaLargerThan3.139<20,239.0,239,0.323410,0.000049

/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)

In [15]:
ABCD_data

                             Bin                     Counts
0    bin A (low NHits, low dPhi)  86.0 +- 9.273618495495704
1   bin B (low NHits, high dPhi)  60.0 +- 7.745966692414834
2   bin C (high NHits, low dPhi)  58.0 +- 7.615773105863909
3  bin D (high NHits, high dPhi)  62.0 +- 7.874007874011811

In [16]:
arr = analysis_helpers.extract_counts_uncs_from_df(ABCD_data)
D_exp, D_exp_unc = analysis_helpers.compute_expected_signal_bin(*arr)
print(f"{D_exp}+-{D_exp_unc}")

40.46511627906977+-8.634913821366647

## Muon

In [17]:
cutflow_data, ABCD_data = Produce_Cutflow_v2.makeCutflow(data_events_mu, cfg_file='mu_VR_DNN/cuts_sensitivity_mu_DNN_VR1.yaml', isMC=False, ABCD=True, blind=False, flavor="Mu", return_branches=False)
cutflow_data

about to compute
entering ABCD code

,Cut Name,Number of Weighted Events,Number of Unweighted Events,Cut Efficiency,Cumulative Efficiency
0,Pass Trigger,20783334.0,20783334,1.000000,1.000000
1,MET>30 GeV,9520061.0,9520061,0.458062,0.458062
2,nLeptons==1,8779321.0,8779321,0.922192,0.422421
3,Lepton is Muon,8757220.0,8757220,0.997483,0.421358
4,"|DeltaR(cluster,mu)|>0.8",1938901.0,1938901,0.221406,0.093291
5,-5ns<clusterTime<12.5ns,1524683.0,1524683,0.786365,0.073361
6,no hits ME11/12,1499999.0,1499999,0.983810,0.072173
7,no matched muon to cluster,1415859.0,1415859,0.943907,0.068125
8,JetVetoPt<10 GeV,1274739.0,1274739,0.900329,0.061335
9,"|dPhi(cluster, MET)|<1.5",640876.0,640876,0.502751,0.030836
10,muPt>15GeV,19052.0,19052,0.029728,0.000917
11,mu pass tightID,15441.0,15441,0.810466,0.000743
12,mu pass looseISO,6300.0,6300,0.408005,0.000303
13,"|DeltaEta(cluster,mu)|<2",4475.0,4475,0.710317,0.000215
14,0.96<DNN<0.99,934.0,934,0.208715,0.000045

/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)

In [18]:
ABCD_data

                             Bin                       Counts
0    bin A (low NHits, low dPhi)  328.0 +- 18.110770276274835
1   bin B (low NHits, high dPhi)  203.0 +- 14.247806848775006
2   bin C (high NHits, low dPhi)  154.0 +- 12.409673645990857
3  bin D (high NHits, high dPhi)  544.0 +- 23.323807579381203

In [19]:
arr = analysis_helpers.extract_counts_uncs_from_df(ABCD_data)
D_exp, D_exp_unc = analysis_helpers.compute_expected_signal_bin(*arr)
print(f"{D_exp}+-{D_exp_unc}")

95.3109756097561+-11.46444668077091

## Tau

### VR no HT

In [20]:
cutflow_data, ABCD_data = Produce_Cutflow_v2.makeCutflow(data_events_tau, cfg_file='tau_VR_DNN/cuts_sensitivity_tau_DNN.yaml', isMC=False, ABCD=True, blind=False, flavor="Tau", return_branches=False)
cutflow_data

about to compute
entering ABCD code

,Cut Name,Number of Weighted Events,Number of Unweighted Events,Cut Efficiency,Cumulative Efficiency
0,Pass Trigger,7462926.0,7462926,1.000000,1.000000
1,MET>30 GeV,3908874.0,3908874,0.523772,0.523772
2,nLeptons==0,3172861.0,3172861,0.811707,0.425150
3,-5ns<clusterTime<12.5ns,2725434.0,2725434,0.858983,0.365196
4,no hits ME11/12,2702309.0,2702309,0.991515,0.362098
5,MuonVetoPt<30GeV,2580530.0,2580530,0.954935,0.345780
6,JetVetoPt<10 GeV,1656120.0,1656120,0.641775,0.221913
7,"|dPhi(cluster, MET)|<1.5",850629.0,850629,0.513628,0.113981
8,exactly 1 tau,780021.0,780021,0.916993,0.104519
9,tauPt>20GeV,671672.0,671672,0.861095,0.090001
10,tau pass tightID,17300.0,17300,0.025757,0.002318
11,"|DeltaEta(cluster,tau)|<2",11103.0,11103,0.641792,0.001488
12,0.96<DNN<0.99,1998.0,1998,0.179951,0.000268

/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)

In [21]:
ABCD_data

                             Bin                       Counts
0    bin A (low NHits, low dPhi)    704.0 +- 26.5329983228432
1   bin B (low NHits, high dPhi)  681.0 +- 26.095976701399778
2   bin C (high NHits, low dPhi)  371.0 +- 19.261360284258224
3  bin D (high NHits, high dPhi)  488.0 +- 22.090722034374522

In [22]:
arr = analysis_helpers.extract_counts_uncs_from_df(ABCD_data)
D_exp, D_exp_unc = analysis_helpers.compute_expected_signal_bin(*arr)
print(f"{D_exp}+-{D_exp_unc}")

358.8792613636364+-26.818394594461196

### VR with HT

In [23]:
cutflow_data, ABCD_data = Produce_Cutflow_v2.makeCutflow(data_events_tau, cfg_file='tau_VR_DNN/cuts_sensitivity_tau_DNN_HT.yaml', isMC=False, ABCD=True, blind=False, flavor="Tau", return_branches=False)
cutflow_data

about to compute
entering ABCD code

,Cut Name,Number of Weighted Events,Number of Unweighted Events,Cut Efficiency,Cumulative Efficiency
0,Pass Trigger,7462926.0,7462926,1.000000,1.000000
1,MET>30 GeV,3908874.0,3908874,0.523772,0.523772
2,nLeptons==0,3172861.0,3172861,0.811707,0.425150
3,-5ns<clusterTime<12.5ns,2725434.0,2725434,0.858983,0.365196
4,no hits ME11/12,2702309.0,2702309,0.991515,0.362098
5,MuonVetoPt<30GeV,2580530.0,2580530,0.954935,0.345780
6,JetVetoPt<10 GeV,1656120.0,1656120,0.641775,0.221913
7,"|dPhi(cluster, MET)|<1.5",850629.0,850629,0.513628,0.113981
8,exactly 1 tau,780021.0,780021,0.916993,0.104519
9,tauPt>20GeV,671672.0,671672,0.861095,0.090001
10,tau pass tightID,17300.0,17300,0.025757,0.002318
11,"|DeltaEta(cluster,tau)|<2",11103.0,11103,0.641792,0.001488
12,0.96<DNN<0.99,1998.0,1998,0.179951,0.000268
13,HTSoftJetsEtaLargerThan3.139<20,633.0,633,0.316817,0.000085

/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/uscms/home/amalbert/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/py3-numpy/1.24.3-0831476b9e4ddf0b4b9eb1f4c971c0d1/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)

In [24]:
ABCD_data

                             Bin                       Counts
0    bin A (low NHits, low dPhi)                196.0 +- 14.0
1   bin B (low NHits, high dPhi)  232.0 +- 15.231546211727817
2   bin C (high NHits, low dPhi)     106.0 +- 10.295630140987
3  bin D (high NHits, high dPhi)  182.0 +- 13.490737563232042

In [25]:
arr = analysis_helpers.extract_counts_uncs_from_df(ABCD_data)
D_exp, D_exp_unc = analysis_helpers.compute_expected_signal_bin(*arr)
print(f"{D_exp}+-{D_exp_unc}")

125.46938775510203+-17.224688665304125